apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: platform-core
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: api-gateway-secrets
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/data/advancia/api-gateway
        property: database_url
    - secretKey: JWT_ACCESS_SECRET
      remoteRef:
        key: secret/data/advancia/api-gateway
        property: jwt_access_secret
