apiVersion: v1
kind: Service
metadata:
  name: tenant-service
  namespace: platform-core
spec:
  selector:
    app: tenant-service
  ports:
    - name: http
      port: 4002
      targetPort: 4002
  type: ClusterIP
