apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: platform-core
spec:
  selector:
    app: monitoring-service
  ports:
    - name: http
      port: 4007
      targetPort: 4007
  type: ClusterIP
