apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: services
spec:
  selector:
    app: billing-service
  ports:
    - name: http
      port: 4003
      targetPort: 4003
  type: ClusterIP
