apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: web3-event-service-secrets
  namespace: platform-core
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: web3-event-service-secrets
  data:
    - secretKey: WEB3_RPC_URL
      remoteRef:
        key: secret/data/advancia/web3-event-service
        property: web3_rpc_url
    - secretKey: ALCHEMY_KEY
      remoteRef:
        key: secret/data/advancia/web3-event-service
        property: alchemy_key
