apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: security-service-policy
  namespace: platform-core
spec:
  podSelector:
    matchLabels:
      app: security-service
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: api-gateway
      ports:
        - protocol: TCP
          port: 4009
    - from:
        - podSelector:
            matchLabels:
              app: admin-console
      ports:
        - protocol: TCP
          port: 4009
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
