apiVersion: v1
kind: Service
metadata:
  name: security-service
  namespace: platform-core
spec:
  selector:
    app: security-service
  ports:
    - name: http
      port: 4009
      targetPort: 4009
  type: ClusterIP
