apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: platform-core
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: auth-service-secrets
  data:
    - secretKey: JWT_ACCESS_SECRET
      remoteRef:
        key: secret/data/advancia/auth-service
        property: jwt_access_secret
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: secret/data/advancia/auth-service
        property: jwt_refresh_secret
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/data/advancia/auth-service
        property: database_url
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/data/advancia/shared
        property: redis_url
    - secretKey: COGNITO_CLIENT_ID
      remoteRef:
        key: secret/data/advancia/auth-service
        property: cognito_client_id
    - secretKey: COGNITO_CLIENT_SECRET
      remoteRef:
        key: secret/data/advancia/auth-service
        property: cognito_client_secret
