apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: platform-core
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/advancia-prod-irsa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: services
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/advancia-prod-irsa-role
