apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - rbac.yaml
  - network-policies.yaml
  - resource-quotas.yaml
  - secret-store.yaml
  - external-secrets-sa.yaml
  - externalsecrets.yaml

commonLabels:
  app.kubernetes.io/part-of: advancia-platform
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: infrastructure
  app.kubernetes.io/name: advancia
