apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: billing-service-secrets
  namespace: platform-core
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: billing-service-secrets
  data:
    - secretKey: STRIPE_KEY
      remoteRef:
        key: secret/data/advancia/billing-service
        property: stripe_key
