apiVersion: v1
kind: Service
metadata:
  name: metering-service
  namespace: services
spec:
  selector:
    app: metering-service
  ports:
    - name: http
      port: 4004
      targetPort: 4004
  type: ClusterIP
