apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - poddisruptionbudgets.yaml
  - horizontalpodautoscalers.yaml
  - api-gateway
  - auth-service
  - tenant-service

commonLabels:
  app.kubernetes.io/part-of: advancia-platform
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/component: platform-core
  app.kubernetes.io/environment: production

namespace: platform-core
