apiVersion: v1
kind: Service
metadata:
  name: web3-event-service
  namespace: services
spec:
  selector:
    app: web3-event-service
  ports:
    - name: http
      port: 4005
      targetPort: 4005
  type: ClusterIP
