apiVersion: v1
kind: Service
metadata:
  name: audit-log-service
  namespace: platform-core
spec:
  selector:
    app: audit-log-service
  ports:
    - name: http
      port: 4010
      targetPort: 4010
  type: ClusterIP
