apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notification-service-secrets
  namespace: platform-core
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: notification-service-secrets
  data:
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: secret/data/advancia/notification-service
        property: smtp_password
    - secretKey: TWILIO_API_KEY
      remoteRef:
        key: secret/data/advancia/notification-service
        property: twilio_api_key
