apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: platform-core
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      port: 4008
      targetPort: 4008
  type: ClusterIP
