apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: metering-service-secrets
  namespace: platform-core
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: metering-service-secrets
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/data/advancia/metering-service
        property: database_url
